// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBot_HL8ae13rR-0hj1h48JtzjPKQy26eo',
    appId: '1:207973705336:web:5d370bb83e3c91e479ef8d',
    messagingSenderId: '207973705336',
    projectId: 'foto-db-bafb0',
    authDomain: 'foto-db-bafb0.firebaseapp.com',
    storageBucket: 'foto-db-bafb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA30nG6ex9-uKCfqCJo6smJ3GtJpPqGENc',
    appId: '1:207973705336:android:95586453e850754c79ef8d',
    messagingSenderId: '207973705336',
    projectId: 'foto-db-bafb0',
    storageBucket: 'foto-db-bafb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQx9JiUl5CbD2cv6j49CFzww8gNiqdZ_o',
    appId: '1:207973705336:ios:b9929e7d51ae8e0779ef8d',
    messagingSenderId: '207973705336',
    projectId: 'foto-db-bafb0',
    storageBucket: 'foto-db-bafb0.firebasestorage.app',
    iosBundleId: 'com.example.tugasmepet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQx9JiUl5CbD2cv6j49CFzww8gNiqdZ_o',
    appId: '1:207973705336:ios:b9929e7d51ae8e0779ef8d',
    messagingSenderId: '207973705336',
    projectId: 'foto-db-bafb0',
    storageBucket: 'foto-db-bafb0.firebasestorage.app',
    iosBundleId: 'com.example.tugasmepet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBot_HL8ae13rR-0hj1h48JtzjPKQy26eo',
    appId: '1:207973705336:web:9781a39c32cb8db979ef8d',
    messagingSenderId: '207973705336',
    projectId: 'foto-db-bafb0',
    authDomain: 'foto-db-bafb0.firebaseapp.com',
    storageBucket: 'foto-db-bafb0.firebasestorage.app',
  );
}
